# Trinquet configuration file

# Storage backend
backend = "boltdb"

[api]
grpcPort = 8080
restPort = 9090

[boltdb]
file = "/tmp/ut.db"
bucket = "trinquet"

[tracing]
name = "zipkin"
# name = "appdash"
# name = "jaeger"

[tracing.zipkin]
host = "127.0.0.1"
port = 9411

# [tracing.appdash]
# host = "127.0.0.1"
# port = 7700

[tracing.jaeger]
host = "127.0.0.1"
port = 9441
