// Code generated by protoc-gen-go. DO NOT EDIT.
// source: league.proto

package v1beta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Discipline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discipline) Reset()         { *m = Discipline{} }
func (m *Discipline) String() string { return proto.CompactTextString(m) }
func (*Discipline) ProtoMessage()    {}
func (*Discipline) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{0}
}
func (m *Discipline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discipline.Unmarshal(m, b)
}
func (m *Discipline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discipline.Marshal(b, m, deterministic)
}
func (dst *Discipline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discipline.Merge(dst, src)
}
func (m *Discipline) XXX_Size() int {
	return xxx_messageInfo_Discipline.Size(m)
}
func (m *Discipline) XXX_DiscardUnknown() {
	xxx_messageInfo_Discipline.DiscardUnknown(m)
}

var xxx_messageInfo_Discipline proto.InternalMessageInfo

func (m *Discipline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Discipline) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Level struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Level) Reset()         { *m = Level{} }
func (m *Level) String() string { return proto.CompactTextString(m) }
func (*Level) ProtoMessage()    {}
func (*Level) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{1}
}
func (m *Level) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Level.Unmarshal(m, b)
}
func (m *Level) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Level.Marshal(b, m, deterministic)
}
func (dst *Level) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Level.Merge(dst, src)
}
func (m *Level) XXX_Size() int {
	return xxx_messageInfo_Level.Size(m)
}
func (m *Level) XXX_DiscardUnknown() {
	xxx_messageInfo_Level.DiscardUnknown(m)
}

var xxx_messageInfo_Level proto.InternalMessageInfo

func (m *Level) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Level) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// League define a pelota league
type League struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              map[string]string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Levels               []*Level          `protobuf:"bytes,3,rep,name=levels,proto3" json:"levels,omitempty"`
	Disciplines          []*Discipline     `protobuf:"bytes,4,rep,name=disciplines,proto3" json:"disciplines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *League) Reset()         { *m = League{} }
func (m *League) String() string { return proto.CompactTextString(m) }
func (*League) ProtoMessage()    {}
func (*League) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{2}
}
func (m *League) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_League.Unmarshal(m, b)
}
func (m *League) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_League.Marshal(b, m, deterministic)
}
func (dst *League) XXX_Merge(src proto.Message) {
	xxx_messageInfo_League.Merge(dst, src)
}
func (m *League) XXX_Size() int {
	return xxx_messageInfo_League.Size(m)
}
func (m *League) XXX_DiscardUnknown() {
	xxx_messageInfo_League.DiscardUnknown(m)
}

var xxx_messageInfo_League proto.InternalMessageInfo

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *League) GetLevels() []*Level {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *League) GetDisciplines() []*Discipline {
	if m != nil {
		return m.Disciplines
	}
	return nil
}

type GetLeaguesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeaguesRequest) Reset()         { *m = GetLeaguesRequest{} }
func (m *GetLeaguesRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaguesRequest) ProtoMessage()    {}
func (*GetLeaguesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{3}
}
func (m *GetLeaguesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaguesRequest.Unmarshal(m, b)
}
func (m *GetLeaguesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaguesRequest.Marshal(b, m, deterministic)
}
func (dst *GetLeaguesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaguesRequest.Merge(dst, src)
}
func (m *GetLeaguesRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeaguesRequest.Size(m)
}
func (m *GetLeaguesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaguesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaguesRequest proto.InternalMessageInfo

func (m *GetLeaguesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeaguesResponse struct {
	Leagues              []*League `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetLeaguesResponse) Reset()         { *m = GetLeaguesResponse{} }
func (m *GetLeaguesResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaguesResponse) ProtoMessage()    {}
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{4}
}
func (m *GetLeaguesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaguesResponse.Unmarshal(m, b)
}
func (m *GetLeaguesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaguesResponse.Marshal(b, m, deterministic)
}
func (dst *GetLeaguesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaguesResponse.Merge(dst, src)
}
func (m *GetLeaguesResponse) XXX_Size() int {
	return xxx_messageInfo_GetLeaguesResponse.Size(m)
}
func (m *GetLeaguesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaguesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaguesResponse proto.InternalMessageInfo

func (m *GetLeaguesResponse) GetLeagues() []*League {
	if m != nil {
		return m.Leagues
	}
	return nil
}

type CreateLeagueResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	League               *League  `protobuf:"bytes,2,opt,name=league,proto3" json:"league,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLeagueResponse) Reset()         { *m = CreateLeagueResponse{} }
func (m *CreateLeagueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLeagueResponse) ProtoMessage()    {}
func (*CreateLeagueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{5}
}
func (m *CreateLeagueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeagueResponse.Unmarshal(m, b)
}
func (m *CreateLeagueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeagueResponse.Marshal(b, m, deterministic)
}
func (dst *CreateLeagueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeagueResponse.Merge(dst, src)
}
func (m *CreateLeagueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLeagueResponse.Size(m)
}
func (m *CreateLeagueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeagueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeagueResponse proto.InternalMessageInfo

func (m *CreateLeagueResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type CreateLeagueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Website              string   `protobuf:"bytes,2,opt,name=website,proto3" json:"website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLeagueRequest) Reset()         { *m = CreateLeagueRequest{} }
func (m *CreateLeagueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLeagueRequest) ProtoMessage()    {}
func (*CreateLeagueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{6}
}
func (m *CreateLeagueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeagueRequest.Unmarshal(m, b)
}
func (m *CreateLeagueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeagueRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLeagueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeagueRequest.Merge(dst, src)
}
func (m *CreateLeagueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLeagueRequest.Size(m)
}
func (m *CreateLeagueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeagueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeagueRequest proto.InternalMessageInfo

func (m *CreateLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLeagueRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeagueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeagueRequest) Reset()         { *m = GetLeagueRequest{} }
func (m *GetLeagueRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeagueRequest) ProtoMessage()    {}
func (*GetLeagueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{7}
}
func (m *GetLeagueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeagueRequest.Unmarshal(m, b)
}
func (m *GetLeagueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeagueRequest.Marshal(b, m, deterministic)
}
func (dst *GetLeagueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeagueRequest.Merge(dst, src)
}
func (m *GetLeagueRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeagueRequest.Size(m)
}
func (m *GetLeagueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeagueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeagueRequest proto.InternalMessageInfo

func (m *GetLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeagueResponse struct {
	League               *League  `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeagueResponse) Reset()         { *m = GetLeagueResponse{} }
func (m *GetLeagueResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeagueResponse) ProtoMessage()    {}
func (*GetLeagueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_8d587331c1f2f627, []int{8}
}
func (m *GetLeagueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeagueResponse.Unmarshal(m, b)
}
func (m *GetLeagueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeagueResponse.Marshal(b, m, deterministic)
}
func (dst *GetLeagueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeagueResponse.Merge(dst, src)
}
func (m *GetLeagueResponse) XXX_Size() int {
	return xxx_messageInfo_GetLeagueResponse.Size(m)
}
func (m *GetLeagueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeagueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeagueResponse proto.InternalMessageInfo

func (m *GetLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

func init() {
	proto.RegisterType((*Discipline)(nil), "v1beta.Discipline")
	proto.RegisterType((*Level)(nil), "v1beta.Level")
	proto.RegisterType((*League)(nil), "v1beta.League")
	proto.RegisterMapType((map[string]string)(nil), "v1beta.League.DetailsEntry")
	proto.RegisterType((*GetLeaguesRequest)(nil), "v1beta.GetLeaguesRequest")
	proto.RegisterType((*GetLeaguesResponse)(nil), "v1beta.GetLeaguesResponse")
	proto.RegisterType((*CreateLeagueResponse)(nil), "v1beta.CreateLeagueResponse")
	proto.RegisterType((*CreateLeagueRequest)(nil), "v1beta.CreateLeagueRequest")
	proto.RegisterType((*GetLeagueRequest)(nil), "v1beta.GetLeagueRequest")
	proto.RegisterType((*GetLeagueResponse)(nil), "v1beta.GetLeagueResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeagueServiceClient is the client API for LeagueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeagueServiceClient interface {
	// List returns all available League
	List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error)
	// Get return a league
	Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error)
}

type leagueServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeagueServiceClient(cc *grpc.ClientConn) LeagueServiceClient {
	return &leagueServiceClient{cc}
}

func (c *leagueServiceClient) List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error) {
	out := new(GetLeaguesResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error) {
	out := new(CreateLeagueResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error) {
	out := new(GetLeagueResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeagueServiceServer is the server API for LeagueService service.
type LeagueServiceServer interface {
	// List returns all available League
	List(context.Context, *GetLeaguesRequest) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(context.Context, *CreateLeagueRequest) (*CreateLeagueResponse, error)
	// Get return a league
	Get(context.Context, *GetLeagueRequest) (*GetLeagueResponse, error)
}

func RegisterLeagueServiceServer(s *grpc.Server, srv LeagueServiceServer) {
	s.RegisterService(&_LeagueService_serviceDesc, srv)
}

func _LeagueService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).List(ctx, req.(*GetLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Create(ctx, req.(*CreateLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Get(ctx, req.(*GetLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeagueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.LeagueService",
	HandlerType: (*LeagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LeagueService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LeagueService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LeagueService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

func init() { proto.RegisterFile("league.proto", fileDescriptor_league_8d587331c1f2f627) }

var fileDescriptor_league_8d587331c1f2f627 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0x25, 0x69, 0x9b, 0xe2, 0xb7, 0x3f, 0xee, 0x7e, 0x16, 0x36, 0x8d, 0x0b, 0x2e, 0x03, 0xae,
	0x45, 0xb0, 0x61, 0xab, 0x82, 0x54, 0xf0, 0x66, 0x57, 0xf6, 0xa6, 0x57, 0x11, 0xbc, 0xf1, 0x42,
	0xa6, 0xcd, 0x47, 0x19, 0x1c, 0x93, 0x9a, 0x99, 0x46, 0x16, 0xf1, 0xc6, 0x57, 0xf0, 0x19, 0x7c,
	0x22, 0x5f, 0xc1, 0x4b, 0x1f, 0x42, 0x32, 0x93, 0xa4, 0x59, 0x1b, 0x8b, 0x77, 0x33, 0x73, 0xce,
	0x77, 0xe6, 0x9c, 0x33, 0x09, 0xec, 0x4b, 0xe2, 0xcb, 0x35, 0x8d, 0x57, 0x59, 0xaa, 0x53, 0xf4,
	0xf2, 0x8b, 0x39, 0x69, 0x1e, 0x9c, 0x2e, 0xd3, 0x74, 0x29, 0x29, 0xe4, 0x2b, 0x11, 0xf2, 0x24,
	0x49, 0x35, 0xd7, 0x22, 0x4d, 0x94, 0x65, 0xb1, 0x09, 0xc0, 0x95, 0x50, 0x0b, 0xb1, 0x92, 0x22,
	0x21, 0x3c, 0x04, 0x57, 0xc4, 0xbe, 0x73, 0xe6, 0x8c, 0xee, 0x44, 0xae, 0x88, 0x71, 0x00, 0x3d,
	0x2d, 0xb4, 0x24, 0xdf, 0x35, 0x47, 0x76, 0xc3, 0x9e, 0x40, 0x6f, 0x46, 0x39, 0xc9, 0xff, 0xa4,
	0xff, 0x76, 0xc0, 0x9b, 0x19, 0x67, 0x88, 0xd0, 0x4d, 0xf8, 0x47, 0x2a, 0x47, 0xcc, 0x1a, 0x9f,
	0x43, 0x3f, 0x26, 0xcd, 0x85, 0x54, 0xbe, 0x7b, 0xd6, 0x19, 0xed, 0x4d, 0xee, 0x8f, 0xad, 0xf3,
	0xb1, 0x1d, 0x1a, 0x5f, 0x59, 0xf4, 0x75, 0xa2, 0xb3, 0x9b, 0xa8, 0xe2, 0xe2, 0x43, 0xf0, 0x64,
	0x61, 0x42, 0xf9, 0x1d, 0x33, 0x75, 0xb0, 0x99, 0xca, 0x49, 0x46, 0x25, 0x88, 0xcf, 0x60, 0x2f,
	0xae, 0xf3, 0x29, 0xbf, 0x6b, 0xb8, 0x58, 0x71, 0x37, 0xd1, 0xa3, 0x26, 0x2d, 0x98, 0xc2, 0x7e,
	0xf3, 0x56, 0x3c, 0x82, 0xce, 0x07, 0xba, 0x29, 0x6d, 0x17, 0xcb, 0x22, 0x6a, 0xce, 0xe5, 0xba,
	0x8e, 0x6a, 0x36, 0x53, 0xf7, 0x85, 0xc3, 0x1e, 0xc1, 0xf1, 0x35, 0x69, 0xeb, 0x5d, 0x45, 0xf4,
	0x69, 0x4d, 0x4a, 0xb7, 0x05, 0x67, 0xaf, 0x00, 0x9b, 0x44, 0xb5, 0x4a, 0x13, 0x45, 0x38, 0x82,
	0xbe, 0x7d, 0x46, 0xe5, 0x3b, 0xc6, 0xec, 0xe1, 0xed, 0x3a, 0xa2, 0x0a, 0x66, 0x11, 0x0c, 0x2e,
	0x33, 0xe2, 0x9a, 0x4a, 0xa0, 0x52, 0x40, 0xe8, 0x2e, 0xd2, 0xd8, 0xde, 0xd5, 0x8b, 0xcc, 0x1a,
	0xcf, 0x8b, 0xb6, 0x0a, 0x96, 0xf1, 0xbb, 0x2d, 0x5a, 0xa2, 0xec, 0x12, 0xee, 0xdd, 0xd6, 0xfc,
	0xa7, 0x7d, 0xf4, 0xa1, 0xff, 0x99, 0xe6, 0x4a, 0xe8, 0xaa, 0x83, 0x6a, 0xcb, 0xce, 0xe1, 0xa8,
	0x0e, 0xb6, 0xab, 0x80, 0x97, 0x8d, 0xa6, 0x6a, 0xf7, 0x1b, 0xa7, 0xce, 0x2e, 0xa7, 0x93, 0x1f,
	0x2e, 0x1c, 0xd8, 0xa3, 0x37, 0x94, 0xe5, 0x62, 0x41, 0xf8, 0x16, 0xba, 0x33, 0xa1, 0x34, 0x0e,
	0xab, 0x89, 0xad, 0x67, 0x08, 0x82, 0x36, 0xc8, 0x5e, 0xcc, 0x4e, 0xbe, 0xfd, 0xfc, 0xf5, 0xdd,
	0x3d, 0xc6, 0xbb, 0xa1, 0xe5, 0x84, 0x65, 0xcf, 0xf8, 0x1e, 0x3c, 0xdb, 0x09, 0xd6, 0x5f, 0x66,
	0x4b, 0x47, 0xc1, 0x69, 0x3b, 0x58, 0xaa, 0x07, 0x46, 0x7d, 0xc0, 0xfe, 0x56, 0x9f, 0x3a, 0x8f,
	0xf1, 0x1d, 0x74, 0xae, 0x49, 0xa3, 0xbf, 0x65, 0xae, 0x92, 0x1e, 0xb6, 0x20, 0xa5, 0xee, 0x03,
	0xa3, 0x3b, 0xc4, 0x93, 0x30, 0xbf, 0x10, 0x4d, 0xe1, 0xf0, 0x4b, 0xd1, 0xf1, 0xd7, 0xb9, 0x67,
	0xfe, 0xf3, 0xa7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x5a, 0xe4, 0x9d, 0x1d, 0x04, 0x00,
	0x00,
}
