// Code generated by protoc-gen-go. DO NOT EDIT.
// source: league.proto

package v1beta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Discipline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discipline) Reset()         { *m = Discipline{} }
func (m *Discipline) String() string { return proto.CompactTextString(m) }
func (*Discipline) ProtoMessage()    {}
func (*Discipline) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{0}
}
func (m *Discipline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discipline.Unmarshal(m, b)
}
func (m *Discipline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discipline.Marshal(b, m, deterministic)
}
func (dst *Discipline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discipline.Merge(dst, src)
}
func (m *Discipline) XXX_Size() int {
	return xxx_messageInfo_Discipline.Size(m)
}
func (m *Discipline) XXX_DiscardUnknown() {
	xxx_messageInfo_Discipline.DiscardUnknown(m)
}

var xxx_messageInfo_Discipline proto.InternalMessageInfo

func (m *Discipline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Discipline) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Level struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Level) Reset()         { *m = Level{} }
func (m *Level) String() string { return proto.CompactTextString(m) }
func (*Level) ProtoMessage()    {}
func (*Level) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{1}
}
func (m *Level) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Level.Unmarshal(m, b)
}
func (m *Level) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Level.Marshal(b, m, deterministic)
}
func (dst *Level) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Level.Merge(dst, src)
}
func (m *Level) XXX_Size() int {
	return xxx_messageInfo_Level.Size(m)
}
func (m *Level) XXX_DiscardUnknown() {
	xxx_messageInfo_Level.DiscardUnknown(m)
}

var xxx_messageInfo_Level proto.InternalMessageInfo

func (m *Level) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Level) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// League define a pelota league
type League struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              map[string]string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Levels               []*Level          `protobuf:"bytes,3,rep,name=levels,proto3" json:"levels,omitempty"`
	Disciplines          []*Discipline     `protobuf:"bytes,4,rep,name=disciplines,proto3" json:"disciplines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *League) Reset()         { *m = League{} }
func (m *League) String() string { return proto.CompactTextString(m) }
func (*League) ProtoMessage()    {}
func (*League) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{2}
}
func (m *League) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_League.Unmarshal(m, b)
}
func (m *League) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_League.Marshal(b, m, deterministic)
}
func (dst *League) XXX_Merge(src proto.Message) {
	xxx_messageInfo_League.Merge(dst, src)
}
func (m *League) XXX_Size() int {
	return xxx_messageInfo_League.Size(m)
}
func (m *League) XXX_DiscardUnknown() {
	xxx_messageInfo_League.DiscardUnknown(m)
}

var xxx_messageInfo_League proto.InternalMessageInfo

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *League) GetLevels() []*Level {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *League) GetDisciplines() []*Discipline {
	if m != nil {
		return m.Disciplines
	}
	return nil
}

type GetLeaguesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeaguesRequest) Reset()         { *m = GetLeaguesRequest{} }
func (m *GetLeaguesRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaguesRequest) ProtoMessage()    {}
func (*GetLeaguesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{3}
}
func (m *GetLeaguesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaguesRequest.Unmarshal(m, b)
}
func (m *GetLeaguesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaguesRequest.Marshal(b, m, deterministic)
}
func (dst *GetLeaguesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaguesRequest.Merge(dst, src)
}
func (m *GetLeaguesRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeaguesRequest.Size(m)
}
func (m *GetLeaguesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaguesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaguesRequest proto.InternalMessageInfo

func (m *GetLeaguesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeaguesResponse struct {
	Leagues              []*League `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetLeaguesResponse) Reset()         { *m = GetLeaguesResponse{} }
func (m *GetLeaguesResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaguesResponse) ProtoMessage()    {}
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{4}
}
func (m *GetLeaguesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaguesResponse.Unmarshal(m, b)
}
func (m *GetLeaguesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaguesResponse.Marshal(b, m, deterministic)
}
func (dst *GetLeaguesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaguesResponse.Merge(dst, src)
}
func (m *GetLeaguesResponse) XXX_Size() int {
	return xxx_messageInfo_GetLeaguesResponse.Size(m)
}
func (m *GetLeaguesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaguesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaguesResponse proto.InternalMessageInfo

func (m *GetLeaguesResponse) GetLeagues() []*League {
	if m != nil {
		return m.Leagues
	}
	return nil
}

type CreateLeagueResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	League               *League  `protobuf:"bytes,2,opt,name=league,proto3" json:"league,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLeagueResponse) Reset()         { *m = CreateLeagueResponse{} }
func (m *CreateLeagueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLeagueResponse) ProtoMessage()    {}
func (*CreateLeagueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{5}
}
func (m *CreateLeagueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeagueResponse.Unmarshal(m, b)
}
func (m *CreateLeagueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeagueResponse.Marshal(b, m, deterministic)
}
func (dst *CreateLeagueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeagueResponse.Merge(dst, src)
}
func (m *CreateLeagueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLeagueResponse.Size(m)
}
func (m *CreateLeagueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeagueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeagueResponse proto.InternalMessageInfo

func (m *CreateLeagueResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type CreateLeagueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Website              string   `protobuf:"bytes,2,opt,name=website,proto3" json:"website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLeagueRequest) Reset()         { *m = CreateLeagueRequest{} }
func (m *CreateLeagueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLeagueRequest) ProtoMessage()    {}
func (*CreateLeagueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{6}
}
func (m *CreateLeagueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeagueRequest.Unmarshal(m, b)
}
func (m *CreateLeagueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeagueRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLeagueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeagueRequest.Merge(dst, src)
}
func (m *CreateLeagueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLeagueRequest.Size(m)
}
func (m *CreateLeagueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeagueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeagueRequest proto.InternalMessageInfo

func (m *CreateLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLeagueRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeagueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeagueRequest) Reset()         { *m = GetLeagueRequest{} }
func (m *GetLeagueRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeagueRequest) ProtoMessage()    {}
func (*GetLeagueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{7}
}
func (m *GetLeagueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeagueRequest.Unmarshal(m, b)
}
func (m *GetLeagueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeagueRequest.Marshal(b, m, deterministic)
}
func (dst *GetLeagueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeagueRequest.Merge(dst, src)
}
func (m *GetLeagueRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeagueRequest.Size(m)
}
func (m *GetLeagueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeagueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeagueRequest proto.InternalMessageInfo

func (m *GetLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeagueResponse struct {
	League               *League  `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeagueResponse) Reset()         { *m = GetLeagueResponse{} }
func (m *GetLeagueResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeagueResponse) ProtoMessage()    {}
func (*GetLeagueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{8}
}
func (m *GetLeagueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeagueResponse.Unmarshal(m, b)
}
func (m *GetLeagueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeagueResponse.Marshal(b, m, deterministic)
}
func (dst *GetLeagueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeagueResponse.Merge(dst, src)
}
func (m *GetLeagueResponse) XXX_Size() int {
	return xxx_messageInfo_GetLeagueResponse.Size(m)
}
func (m *GetLeagueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeagueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeagueResponse proto.InternalMessageInfo

func (m *GetLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type Team struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{9}
}
func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (dst *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(dst, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Group struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team                 []*Team  `protobuf:"bytes,3,rep,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{10}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetTeam() []*Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type Round struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	First                *Team    `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Second               *Team    `protobuf:"bytes,3,opt,name=second,proto3" json:"second,omitempty"`
	Score                string   `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{11}
}
func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (dst *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(dst, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Round) GetFirst() *Team {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *Round) GetSecond() *Team {
	if m != nil {
		return m.Second
	}
	return nil
}

func (m *Round) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

// Tournament define a pelota league
type Tournament struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Groups               map[string]*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rounds               []*Round          `protobuf:"bytes,3,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Tournament) Reset()         { *m = Tournament{} }
func (m *Tournament) String() string { return proto.CompactTextString(m) }
func (*Tournament) ProtoMessage()    {}
func (*Tournament) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{12}
}
func (m *Tournament) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tournament.Unmarshal(m, b)
}
func (m *Tournament) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tournament.Marshal(b, m, deterministic)
}
func (dst *Tournament) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tournament.Merge(dst, src)
}
func (m *Tournament) XXX_Size() int {
	return xxx_messageInfo_Tournament.Size(m)
}
func (m *Tournament) XXX_DiscardUnknown() {
	xxx_messageInfo_Tournament.DiscardUnknown(m)
}

var xxx_messageInfo_Tournament proto.InternalMessageInfo

func (m *Tournament) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tournament) GetGroups() map[string]*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Tournament) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type GetTournamentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTournamentsRequest) Reset()         { *m = GetTournamentsRequest{} }
func (m *GetTournamentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTournamentsRequest) ProtoMessage()    {}
func (*GetTournamentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{13}
}
func (m *GetTournamentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTournamentsRequest.Unmarshal(m, b)
}
func (m *GetTournamentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTournamentsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTournamentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTournamentsRequest.Merge(dst, src)
}
func (m *GetTournamentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTournamentsRequest.Size(m)
}
func (m *GetTournamentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTournamentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTournamentsRequest proto.InternalMessageInfo

type GetTournamentsResponse struct {
	Tournaments          []*Tournament `protobuf:"bytes,1,rep,name=tournaments,proto3" json:"tournaments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetTournamentsResponse) Reset()         { *m = GetTournamentsResponse{} }
func (m *GetTournamentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTournamentsResponse) ProtoMessage()    {}
func (*GetTournamentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{14}
}
func (m *GetTournamentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTournamentsResponse.Unmarshal(m, b)
}
func (m *GetTournamentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTournamentsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTournamentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTournamentsResponse.Merge(dst, src)
}
func (m *GetTournamentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTournamentsResponse.Size(m)
}
func (m *GetTournamentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTournamentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTournamentsResponse proto.InternalMessageInfo

func (m *GetTournamentsResponse) GetTournaments() []*Tournament {
	if m != nil {
		return m.Tournaments
	}
	return nil
}

type GetTournamentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTournamentRequest) Reset()         { *m = GetTournamentRequest{} }
func (m *GetTournamentRequest) String() string { return proto.CompactTextString(m) }
func (*GetTournamentRequest) ProtoMessage()    {}
func (*GetTournamentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{15}
}
func (m *GetTournamentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTournamentRequest.Unmarshal(m, b)
}
func (m *GetTournamentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTournamentRequest.Marshal(b, m, deterministic)
}
func (dst *GetTournamentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTournamentRequest.Merge(dst, src)
}
func (m *GetTournamentRequest) XXX_Size() int {
	return xxx_messageInfo_GetTournamentRequest.Size(m)
}
func (m *GetTournamentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTournamentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTournamentRequest proto.InternalMessageInfo

func (m *GetTournamentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTournamentResponse struct {
	Tournament           *Tournament `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTournamentResponse) Reset()         { *m = GetTournamentResponse{} }
func (m *GetTournamentResponse) String() string { return proto.CompactTextString(m) }
func (*GetTournamentResponse) ProtoMessage()    {}
func (*GetTournamentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{16}
}
func (m *GetTournamentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTournamentResponse.Unmarshal(m, b)
}
func (m *GetTournamentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTournamentResponse.Marshal(b, m, deterministic)
}
func (dst *GetTournamentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTournamentResponse.Merge(dst, src)
}
func (m *GetTournamentResponse) XXX_Size() int {
	return xxx_messageInfo_GetTournamentResponse.Size(m)
}
func (m *GetTournamentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTournamentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTournamentResponse proto.InternalMessageInfo

func (m *GetTournamentResponse) GetTournament() *Tournament {
	if m != nil {
		return m.Tournament
	}
	return nil
}

type CreateTournamentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Groups               []*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTournamentRequest) Reset()         { *m = CreateTournamentRequest{} }
func (m *CreateTournamentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTournamentRequest) ProtoMessage()    {}
func (*CreateTournamentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{17}
}
func (m *CreateTournamentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTournamentRequest.Unmarshal(m, b)
}
func (m *CreateTournamentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTournamentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTournamentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTournamentRequest.Merge(dst, src)
}
func (m *CreateTournamentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTournamentRequest.Size(m)
}
func (m *CreateTournamentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTournamentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTournamentRequest proto.InternalMessageInfo

func (m *CreateTournamentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTournamentRequest) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateTournamentResponse struct {
	Tournament           *Tournament `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateTournamentResponse) Reset()         { *m = CreateTournamentResponse{} }
func (m *CreateTournamentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTournamentResponse) ProtoMessage()    {}
func (*CreateTournamentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_league_43a47aa3872077de, []int{18}
}
func (m *CreateTournamentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTournamentResponse.Unmarshal(m, b)
}
func (m *CreateTournamentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTournamentResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTournamentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTournamentResponse.Merge(dst, src)
}
func (m *CreateTournamentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTournamentResponse.Size(m)
}
func (m *CreateTournamentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTournamentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTournamentResponse proto.InternalMessageInfo

func (m *CreateTournamentResponse) GetTournament() *Tournament {
	if m != nil {
		return m.Tournament
	}
	return nil
}

func init() {
	proto.RegisterType((*Discipline)(nil), "v1beta.Discipline")
	proto.RegisterType((*Level)(nil), "v1beta.Level")
	proto.RegisterType((*League)(nil), "v1beta.League")
	proto.RegisterMapType((map[string]string)(nil), "v1beta.League.DetailsEntry")
	proto.RegisterType((*GetLeaguesRequest)(nil), "v1beta.GetLeaguesRequest")
	proto.RegisterType((*GetLeaguesResponse)(nil), "v1beta.GetLeaguesResponse")
	proto.RegisterType((*CreateLeagueResponse)(nil), "v1beta.CreateLeagueResponse")
	proto.RegisterType((*CreateLeagueRequest)(nil), "v1beta.CreateLeagueRequest")
	proto.RegisterType((*GetLeagueRequest)(nil), "v1beta.GetLeagueRequest")
	proto.RegisterType((*GetLeagueResponse)(nil), "v1beta.GetLeagueResponse")
	proto.RegisterType((*Team)(nil), "v1beta.Team")
	proto.RegisterType((*Group)(nil), "v1beta.Group")
	proto.RegisterType((*Round)(nil), "v1beta.Round")
	proto.RegisterType((*Tournament)(nil), "v1beta.Tournament")
	proto.RegisterMapType((map[string]*Group)(nil), "v1beta.Tournament.GroupsEntry")
	proto.RegisterType((*GetTournamentsRequest)(nil), "v1beta.GetTournamentsRequest")
	proto.RegisterType((*GetTournamentsResponse)(nil), "v1beta.GetTournamentsResponse")
	proto.RegisterType((*GetTournamentRequest)(nil), "v1beta.GetTournamentRequest")
	proto.RegisterType((*GetTournamentResponse)(nil), "v1beta.GetTournamentResponse")
	proto.RegisterType((*CreateTournamentRequest)(nil), "v1beta.CreateTournamentRequest")
	proto.RegisterType((*CreateTournamentResponse)(nil), "v1beta.CreateTournamentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeagueServiceClient is the client API for LeagueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeagueServiceClient interface {
	// List returns all available League
	List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error)
	// Get return a league
	Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error)
}

type leagueServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeagueServiceClient(cc *grpc.ClientConn) LeagueServiceClient {
	return &leagueServiceClient{cc}
}

func (c *leagueServiceClient) List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error) {
	out := new(GetLeaguesResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error) {
	out := new(CreateLeagueResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error) {
	out := new(GetLeagueResponse)
	err := c.cc.Invoke(ctx, "/v1beta.LeagueService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeagueServiceServer is the server API for LeagueService service.
type LeagueServiceServer interface {
	// List returns all available League
	List(context.Context, *GetLeaguesRequest) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(context.Context, *CreateLeagueRequest) (*CreateLeagueResponse, error)
	// Get return a league
	Get(context.Context, *GetLeagueRequest) (*GetLeagueResponse, error)
}

func RegisterLeagueServiceServer(s *grpc.Server, srv LeagueServiceServer) {
	s.RegisterService(&_LeagueService_serviceDesc, srv)
}

func _LeagueService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).List(ctx, req.(*GetLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Create(ctx, req.(*CreateLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Get(ctx, req.(*GetLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeagueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.LeagueService",
	HandlerType: (*LeagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LeagueService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LeagueService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LeagueService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

// TournamentServiceClient is the client API for TournamentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TournamentServiceClient interface {
	// List returns all available Tournament
	List(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error)
	// Create creates a new tournament
	Create(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*CreateTournamentResponse, error)
	// Get return a tournament
	Get(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*GetTournamentResponse, error)
}

type tournamentServiceClient struct {
	cc *grpc.ClientConn
}

func NewTournamentServiceClient(cc *grpc.ClientConn) TournamentServiceClient {
	return &tournamentServiceClient{cc}
}

func (c *tournamentServiceClient) List(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error) {
	out := new(GetTournamentsResponse)
	err := c.cc.Invoke(ctx, "/v1beta.TournamentService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) Create(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*CreateTournamentResponse, error) {
	out := new(CreateTournamentResponse)
	err := c.cc.Invoke(ctx, "/v1beta.TournamentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) Get(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*GetTournamentResponse, error) {
	out := new(GetTournamentResponse)
	err := c.cc.Invoke(ctx, "/v1beta.TournamentService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TournamentServiceServer is the server API for TournamentService service.
type TournamentServiceServer interface {
	// List returns all available Tournament
	List(context.Context, *GetTournamentsRequest) (*GetTournamentsResponse, error)
	// Create creates a new tournament
	Create(context.Context, *CreateTournamentRequest) (*CreateTournamentResponse, error)
	// Get return a tournament
	Get(context.Context, *GetTournamentRequest) (*GetTournamentResponse, error)
}

func RegisterTournamentServiceServer(s *grpc.Server, srv TournamentServiceServer) {
	s.RegisterService(&_TournamentService_serviceDesc, srv)
}

func _TournamentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).List(ctx, req.(*GetTournamentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).Create(ctx, req.(*CreateTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).Get(ctx, req.(*GetTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TournamentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.TournamentService",
	HandlerType: (*TournamentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TournamentService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TournamentService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TournamentService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

func init() { proto.RegisterFile("league.proto", fileDescriptor_league_43a47aa3872077de) }

var fileDescriptor_league_43a47aa3872077de = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x9d, 0x3f, 0xd5, 0x6f, 0xd2, 0xf6, 0xd7, 0x4e, 0x53, 0xe2, 0xba, 0x69, 0x1b, 0x2d,
	0x50, 0xaa, 0x4a, 0x24, 0x6a, 0x28, 0x08, 0x15, 0xc1, 0xa5, 0x45, 0x41, 0xa2, 0xea, 0xc1, 0x54,
	0x5c, 0x38, 0x20, 0x27, 0xd9, 0x46, 0x56, 0x5d, 0x3b, 0x78, 0x37, 0x41, 0x55, 0xc5, 0x85, 0x57,
	0xe0, 0x19, 0x78, 0x18, 0x24, 0x6e, 0xbc, 0x02, 0x47, 0x1e, 0x02, 0x79, 0x77, 0xed, 0x38, 0xf1,
	0xa6, 0xaa, 0xb8, 0x79, 0xf3, 0xcd, 0x7c, 0xf3, 0xcd, 0xb7, 0x33, 0xab, 0xc0, 0xa2, 0x4f, 0xdd,
	0xc1, 0x88, 0x36, 0x87, 0x51, 0xc8, 0x43, 0x2c, 0x8f, 0x0f, 0xba, 0x94, 0xbb, 0x76, 0x7d, 0x10,
	0x86, 0x03, 0x9f, 0xb6, 0xdc, 0xa1, 0xd7, 0x72, 0x83, 0x20, 0xe4, 0x2e, 0xf7, 0xc2, 0x80, 0xc9,
	0x28, 0xd2, 0x06, 0x38, 0xf1, 0x58, 0xcf, 0x1b, 0xfa, 0x5e, 0x40, 0x71, 0x19, 0x4c, 0xaf, 0x6f,
	0x19, 0x0d, 0x63, 0xef, 0x3f, 0xc7, 0xf4, 0xfa, 0x58, 0x85, 0x12, 0xf7, 0xb8, 0x4f, 0x2d, 0x53,
	0xfc, 0x24, 0x0f, 0xe4, 0x31, 0x94, 0x4e, 0xe9, 0x98, 0xfa, 0x77, 0x0c, 0xff, 0x63, 0x40, 0xf9,
	0x54, 0x28, 0x43, 0x84, 0x62, 0xe0, 0x5e, 0x51, 0x95, 0x22, 0xbe, 0xf1, 0x29, 0x2c, 0xf4, 0x29,
	0x77, 0x3d, 0x9f, 0x59, 0x66, 0xa3, 0xb0, 0x57, 0x69, 0x6f, 0x36, 0xa5, 0xf2, 0xa6, 0x4c, 0x6a,
	0x9e, 0x48, 0xf4, 0x75, 0xc0, 0xa3, 0x6b, 0x27, 0x89, 0xc5, 0x87, 0x50, 0xf6, 0x63, 0x11, 0xcc,
	0x2a, 0x88, 0xac, 0xa5, 0x49, 0xd6, 0x98, 0xfa, 0x8e, 0x02, 0xf1, 0x10, 0x2a, 0xfd, 0xb4, 0x3f,
	0x66, 0x15, 0x45, 0x2c, 0x26, 0xb1, 0x93, 0xd6, 0x9d, 0x6c, 0x98, 0x7d, 0x04, 0x8b, 0xd9, 0xaa,
	0xb8, 0x02, 0x85, 0x4b, 0x7a, 0xad, 0x64, 0xc7, 0x9f, 0x71, 0xab, 0x63, 0xd7, 0x1f, 0xa5, 0xad,
	0x8a, 0xc3, 0x91, 0xf9, 0xdc, 0x20, 0x8f, 0x60, 0xb5, 0x43, 0xb9, 0xd4, 0xce, 0x1c, 0xfa, 0x69,
	0x44, 0x19, 0xd7, 0x35, 0x4e, 0x5e, 0x01, 0x66, 0x03, 0xd9, 0x30, 0x0c, 0x18, 0xc5, 0x3d, 0x58,
	0x90, 0xd7, 0xc8, 0x2c, 0x43, 0x88, 0x5d, 0x9e, 0xb6, 0xc3, 0x49, 0x60, 0xe2, 0x40, 0xf5, 0x38,
	0xa2, 0x2e, 0xa7, 0x0a, 0x48, 0x18, 0x10, 0x8a, 0xbd, 0xb0, 0x2f, 0x6b, 0x95, 0x1c, 0xf1, 0x8d,
	0xbb, 0xb1, 0x5b, 0x71, 0x94, 0xd0, 0x9b, 0x27, 0x55, 0x28, 0x39, 0x86, 0xb5, 0x69, 0xce, 0xb9,
	0xf2, 0xd1, 0x82, 0x85, 0xcf, 0xb4, 0xcb, 0x3c, 0x9e, 0x78, 0x90, 0x1c, 0xc9, 0x2e, 0xac, 0xa4,
	0x8d, 0xdd, 0x66, 0xc0, 0x8b, 0x8c, 0x53, 0xa9, 0xfa, 0x89, 0x52, 0xe3, 0x56, 0xa5, 0x36, 0x14,
	0xcf, 0xa9, 0x7b, 0xa5, 0x25, 0x7e, 0x09, 0xa5, 0x4e, 0x14, 0x8e, 0x86, 0x5a, 0xdd, 0x0d, 0x28,
	0x72, 0xea, 0x5e, 0xa9, 0xb1, 0x59, 0x4c, 0xe8, 0x63, 0x32, 0x47, 0x20, 0xe4, 0x06, 0x4a, 0x4e,
	0x38, 0x0a, 0xfa, 0xda, 0x74, 0x02, 0xa5, 0x0b, 0x2f, 0x62, 0x5c, 0x19, 0x39, 0x9d, 0x2f, 0x21,
	0x7c, 0x00, 0x65, 0x46, 0x7b, 0x61, 0xd0, 0xb7, 0x0a, 0x9a, 0x20, 0x85, 0xc5, 0x23, 0xc4, 0x7a,
	0x61, 0x44, 0xad, 0xa2, 0x1c, 0x21, 0x71, 0x20, 0x3f, 0x0c, 0x80, 0xf3, 0x70, 0x14, 0xc5, 0xc5,
	0x02, 0xbd, 0xf3, 0xcf, 0xa0, 0x3c, 0x88, 0xdb, 0x4b, 0x16, 0x66, 0x3b, 0xa5, 0x4f, 0xf3, 0x9a,
	0xa2, 0x7f, 0xb5, 0x33, 0x2a, 0x3a, 0x5e, 0x99, 0x28, 0xee, 0x2b, 0xb7, 0x32, 0xa2, 0x5b, 0x47,
	0x81, 0xf6, 0x1b, 0xa8, 0x64, 0xb2, 0x35, 0xb3, 0x7f, 0x3f, 0x3b, 0xfb, 0x19, 0x1a, 0x91, 0x95,
	0x5d, 0x85, 0x1a, 0xac, 0x77, 0x28, 0x9f, 0xa8, 0x4a, 0xd6, 0x81, 0x9c, 0xc1, 0xbd, 0x59, 0x40,
	0x5d, 0xff, 0x21, 0x54, 0xf8, 0xe4, 0x67, 0xb5, 0x02, 0x98, 0x6f, 0xd0, 0xc9, 0x86, 0x91, 0x7d,
	0xa8, 0x4e, 0xf1, 0xdd, 0x36, 0x75, 0x6f, 0x67, 0x44, 0xa5, 0xa5, 0xdb, 0x00, 0x13, 0x4e, 0x35,
	0x7d, 0xba, 0xca, 0x99, 0x28, 0x72, 0x0e, 0x35, 0xb9, 0x2f, 0x77, 0xaa, 0x1d, 0xdf, 0xc0, 0xd4,
	0xcd, 0xcd, 0x58, 0xa7, 0x40, 0x72, 0x06, 0x56, 0x9e, 0xf5, 0xdf, 0x55, 0xb6, 0xbf, 0x9b, 0xb0,
	0x24, 0xd7, 0xe7, 0x1d, 0x8d, 0xc6, 0x5e, 0x8f, 0xe2, 0x7b, 0x28, 0x9e, 0x7a, 0x8c, 0xe3, 0x46,
	0x2a, 0x60, 0xf6, 0xc9, 0xb2, 0x6d, 0x1d, 0x24, 0x45, 0x90, 0xda, 0xd7, 0x5f, 0xbf, 0xbf, 0x99,
	0xab, 0xf8, 0x7f, 0x4b, 0xc6, 0xb4, 0xd4, 0x9b, 0x84, 0x1f, 0xa1, 0x2c, 0x95, 0x63, 0xfa, 0x8a,
	0x6b, 0xde, 0x13, 0xbb, 0xae, 0x07, 0x15, 0xbb, 0x2d, 0xd8, 0xab, 0x64, 0x96, 0xfd, 0xc8, 0xd8,
	0xc7, 0x0f, 0x50, 0xe8, 0x50, 0x8e, 0x56, 0x4e, 0x5c, 0x42, 0xbd, 0xa1, 0x41, 0x14, 0xef, 0x8e,
	0xe0, 0xdd, 0xc0, 0x5a, 0x6b, 0x7c, 0xe0, 0x65, 0x89, 0x5b, 0x37, 0xb1, 0x51, 0x5f, 0xda, 0x3f,
	0x4d, 0x58, 0x9d, 0x58, 0x98, 0x78, 0xd5, 0x55, 0x5e, 0x6d, 0x65, 0x98, 0xf3, 0x33, 0x6d, 0x6f,
	0xcf, 0x83, 0x55, 0xf5, 0x4d, 0x51, 0x7d, 0x1d, 0xd7, 0x92, 0xae, 0x32, 0x03, 0x8c, 0x97, 0xa9,
	0x6f, 0x3b, 0xd3, 0xd6, 0xe4, 0xe6, 0xca, 0x6e, 0xcc, 0x0f, 0x50, 0x95, 0xb6, 0x45, 0x25, 0x8b,
	0xe8, 0x2a, 0xc5, 0x1e, 0x5e, 0x48, 0x0f, 0xeb, 0x5a, 0xc1, 0x49, 0x99, 0xad, 0x39, 0xa8, 0xaa,
	0x41, 0x44, 0x8d, 0x3a, 0xda, 0x9a, 0x1a, 0xca, 0xce, 0x6e, 0x59, 0xfc, 0xc5, 0x78, 0xf2, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x1c, 0x1c, 0x77, 0x98, 0x08, 0x00, 0x00,
}
