// Code generated by protoc-gen-go.
// source: league.proto
// DO NOT EDIT!

/*
Package v1beta is a generated protocol buffer package.

It is generated from these files:
	league.proto

It has these top-level messages:
	Discipline
	Level
	League
	GetLeaguesRequest
	GetLeaguesResponse
	CreateLeagueResponse
	CreateLeagueRequest
	GetLeagueRequest
	GetLeagueResponse
	Team
	Group
	Round
	Tournament
	GetTournamentsRequest
	GetTournamentsResponse
	GetTournamentRequest
	GetTournamentResponse
	CreateTournamentRequest
	CreateTournamentResponse
*/
package v1beta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Discipline struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Discipline) Reset()                    { *m = Discipline{} }
func (m *Discipline) String() string            { return proto.CompactTextString(m) }
func (*Discipline) ProtoMessage()               {}
func (*Discipline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Discipline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Discipline) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Level struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Level) Reset()                    { *m = Level{} }
func (m *Level) String() string            { return proto.CompactTextString(m) }
func (*Level) ProtoMessage()               {}
func (*Level) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Level) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Level) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// League define a pelota league
type League struct {
	Name        string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Details     map[string]string `protobuf:"bytes,2,rep,name=details" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Levels      []*Level          `protobuf:"bytes,3,rep,name=levels" json:"levels,omitempty"`
	Disciplines []*Discipline     `protobuf:"bytes,4,rep,name=disciplines" json:"disciplines,omitempty"`
}

func (m *League) Reset()                    { *m = League{} }
func (m *League) String() string            { return proto.CompactTextString(m) }
func (*League) ProtoMessage()               {}
func (*League) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *League) GetLevels() []*Level {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *League) GetDisciplines() []*Discipline {
	if m != nil {
		return m.Disciplines
	}
	return nil
}

type GetLeaguesRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeaguesRequest) Reset()                    { *m = GetLeaguesRequest{} }
func (m *GetLeaguesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesRequest) ProtoMessage()               {}
func (*GetLeaguesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetLeaguesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeaguesResponse struct {
	Leagues []*League `protobuf:"bytes,1,rep,name=leagues" json:"leagues,omitempty"`
}

func (m *GetLeaguesResponse) Reset()                    { *m = GetLeaguesResponse{} }
func (m *GetLeaguesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesResponse) ProtoMessage()               {}
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetLeaguesResponse) GetLeagues() []*League {
	if m != nil {
		return m.Leagues
	}
	return nil
}

type CreateLeagueResponse struct {
	Code   int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	League *League `protobuf:"bytes,2,opt,name=league" json:"league,omitempty"`
}

func (m *CreateLeagueResponse) Reset()                    { *m = CreateLeagueResponse{} }
func (m *CreateLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueResponse) ProtoMessage()               {}
func (*CreateLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateLeagueResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type CreateLeagueRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Website string `protobuf:"bytes,2,opt,name=website" json:"website,omitempty"`
}

func (m *CreateLeagueRequest) Reset()                    { *m = CreateLeagueRequest{} }
func (m *CreateLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueRequest) ProtoMessage()               {}
func (*CreateLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLeagueRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeagueRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeagueRequest) Reset()                    { *m = GetLeagueRequest{} }
func (m *GetLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueRequest) ProtoMessage()               {}
func (*GetLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeagueResponse struct {
	League *League `protobuf:"bytes,1,opt,name=league" json:"league,omitempty"`
}

func (m *GetLeagueResponse) Reset()                    { *m = GetLeagueResponse{} }
func (m *GetLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueResponse) ProtoMessage()               {}
func (*GetLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type Team struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Team) Reset()                    { *m = Team{} }
func (m *Team) String() string            { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()               {}
func (*Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Group struct {
	Name string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Team []*Team `protobuf:"bytes,3,rep,name=team" json:"team,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetTeam() []*Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type Round struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	First  *Team  `protobuf:"bytes,2,opt,name=first" json:"first,omitempty"`
	Second *Team  `protobuf:"bytes,3,opt,name=second" json:"second,omitempty"`
	Score  string `protobuf:"bytes,4,opt,name=score" json:"score,omitempty"`
}

func (m *Round) Reset()                    { *m = Round{} }
func (m *Round) String() string            { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()               {}
func (*Round) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Round) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Round) GetFirst() *Team {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *Round) GetSecond() *Team {
	if m != nil {
		return m.Second
	}
	return nil
}

func (m *Round) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

// Tournament define a pelota league
type Tournament struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Groups map[string]*Group `protobuf:"bytes,2,rep,name=groups" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rounds []*Round          `protobuf:"bytes,3,rep,name=rounds" json:"rounds,omitempty"`
}

func (m *Tournament) Reset()                    { *m = Tournament{} }
func (m *Tournament) String() string            { return proto.CompactTextString(m) }
func (*Tournament) ProtoMessage()               {}
func (*Tournament) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Tournament) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tournament) GetGroups() map[string]*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Tournament) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type GetTournamentsRequest struct {
}

func (m *GetTournamentsRequest) Reset()                    { *m = GetTournamentsRequest{} }
func (m *GetTournamentsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTournamentsRequest) ProtoMessage()               {}
func (*GetTournamentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetTournamentsResponse struct {
	Tournaments []*Tournament `protobuf:"bytes,1,rep,name=tournaments" json:"tournaments,omitempty"`
}

func (m *GetTournamentsResponse) Reset()                    { *m = GetTournamentsResponse{} }
func (m *GetTournamentsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTournamentsResponse) ProtoMessage()               {}
func (*GetTournamentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetTournamentsResponse) GetTournaments() []*Tournament {
	if m != nil {
		return m.Tournaments
	}
	return nil
}

type GetTournamentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetTournamentRequest) Reset()                    { *m = GetTournamentRequest{} }
func (m *GetTournamentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTournamentRequest) ProtoMessage()               {}
func (*GetTournamentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetTournamentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTournamentResponse struct {
	Tournament *Tournament `protobuf:"bytes,1,opt,name=tournament" json:"tournament,omitempty"`
}

func (m *GetTournamentResponse) Reset()                    { *m = GetTournamentResponse{} }
func (m *GetTournamentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTournamentResponse) ProtoMessage()               {}
func (*GetTournamentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetTournamentResponse) GetTournament() *Tournament {
	if m != nil {
		return m.Tournament
	}
	return nil
}

type CreateTournamentRequest struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Groups []*Group `protobuf:"bytes,2,rep,name=groups" json:"groups,omitempty"`
}

func (m *CreateTournamentRequest) Reset()                    { *m = CreateTournamentRequest{} }
func (m *CreateTournamentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTournamentRequest) ProtoMessage()               {}
func (*CreateTournamentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreateTournamentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTournamentRequest) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateTournamentResponse struct {
	Tournament *Tournament `protobuf:"bytes,1,opt,name=tournament" json:"tournament,omitempty"`
}

func (m *CreateTournamentResponse) Reset()                    { *m = CreateTournamentResponse{} }
func (m *CreateTournamentResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTournamentResponse) ProtoMessage()               {}
func (*CreateTournamentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreateTournamentResponse) GetTournament() *Tournament {
	if m != nil {
		return m.Tournament
	}
	return nil
}

func init() {
	proto.RegisterType((*Discipline)(nil), "v1beta.Discipline")
	proto.RegisterType((*Level)(nil), "v1beta.Level")
	proto.RegisterType((*League)(nil), "v1beta.League")
	proto.RegisterType((*GetLeaguesRequest)(nil), "v1beta.GetLeaguesRequest")
	proto.RegisterType((*GetLeaguesResponse)(nil), "v1beta.GetLeaguesResponse")
	proto.RegisterType((*CreateLeagueResponse)(nil), "v1beta.CreateLeagueResponse")
	proto.RegisterType((*CreateLeagueRequest)(nil), "v1beta.CreateLeagueRequest")
	proto.RegisterType((*GetLeagueRequest)(nil), "v1beta.GetLeagueRequest")
	proto.RegisterType((*GetLeagueResponse)(nil), "v1beta.GetLeagueResponse")
	proto.RegisterType((*Team)(nil), "v1beta.Team")
	proto.RegisterType((*Group)(nil), "v1beta.Group")
	proto.RegisterType((*Round)(nil), "v1beta.Round")
	proto.RegisterType((*Tournament)(nil), "v1beta.Tournament")
	proto.RegisterType((*GetTournamentsRequest)(nil), "v1beta.GetTournamentsRequest")
	proto.RegisterType((*GetTournamentsResponse)(nil), "v1beta.GetTournamentsResponse")
	proto.RegisterType((*GetTournamentRequest)(nil), "v1beta.GetTournamentRequest")
	proto.RegisterType((*GetTournamentResponse)(nil), "v1beta.GetTournamentResponse")
	proto.RegisterType((*CreateTournamentRequest)(nil), "v1beta.CreateTournamentRequest")
	proto.RegisterType((*CreateTournamentResponse)(nil), "v1beta.CreateTournamentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LeagueService service

type LeagueServiceClient interface {
	// List returns all available League
	List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error)
	// Get return a league
	Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error)
}

type leagueServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeagueServiceClient(cc *grpc.ClientConn) LeagueServiceClient {
	return &leagueServiceClient{cc}
}

func (c *leagueServiceClient) List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error) {
	out := new(GetLeaguesResponse)
	err := grpc.Invoke(ctx, "/v1beta.LeagueService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error) {
	out := new(CreateLeagueResponse)
	err := grpc.Invoke(ctx, "/v1beta.LeagueService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error) {
	out := new(GetLeagueResponse)
	err := grpc.Invoke(ctx, "/v1beta.LeagueService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LeagueService service

type LeagueServiceServer interface {
	// List returns all available League
	List(context.Context, *GetLeaguesRequest) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(context.Context, *CreateLeagueRequest) (*CreateLeagueResponse, error)
	// Get return a league
	Get(context.Context, *GetLeagueRequest) (*GetLeagueResponse, error)
}

func RegisterLeagueServiceServer(s *grpc.Server, srv LeagueServiceServer) {
	s.RegisterService(&_LeagueService_serviceDesc, srv)
}

func _LeagueService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).List(ctx, req.(*GetLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Create(ctx, req.(*CreateLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.LeagueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Get(ctx, req.(*GetLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeagueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.LeagueService",
	HandlerType: (*LeagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LeagueService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LeagueService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LeagueService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

// Client API for TournamentService service

type TournamentServiceClient interface {
	// List returns all available Tournament
	List(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error)
	// Create creates a new tournament
	Create(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*CreateTournamentResponse, error)
	// Get return a tournament
	Get(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*GetTournamentResponse, error)
}

type tournamentServiceClient struct {
	cc *grpc.ClientConn
}

func NewTournamentServiceClient(cc *grpc.ClientConn) TournamentServiceClient {
	return &tournamentServiceClient{cc}
}

func (c *tournamentServiceClient) List(ctx context.Context, in *GetTournamentsRequest, opts ...grpc.CallOption) (*GetTournamentsResponse, error) {
	out := new(GetTournamentsResponse)
	err := grpc.Invoke(ctx, "/v1beta.TournamentService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) Create(ctx context.Context, in *CreateTournamentRequest, opts ...grpc.CallOption) (*CreateTournamentResponse, error) {
	out := new(CreateTournamentResponse)
	err := grpc.Invoke(ctx, "/v1beta.TournamentService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) Get(ctx context.Context, in *GetTournamentRequest, opts ...grpc.CallOption) (*GetTournamentResponse, error) {
	out := new(GetTournamentResponse)
	err := grpc.Invoke(ctx, "/v1beta.TournamentService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TournamentService service

type TournamentServiceServer interface {
	// List returns all available Tournament
	List(context.Context, *GetTournamentsRequest) (*GetTournamentsResponse, error)
	// Create creates a new tournament
	Create(context.Context, *CreateTournamentRequest) (*CreateTournamentResponse, error)
	// Get return a tournament
	Get(context.Context, *GetTournamentRequest) (*GetTournamentResponse, error)
}

func RegisterTournamentServiceServer(s *grpc.Server, srv TournamentServiceServer) {
	s.RegisterService(&_TournamentService_serviceDesc, srv)
}

func _TournamentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).List(ctx, req.(*GetTournamentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).Create(ctx, req.(*CreateTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.TournamentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).Get(ctx, req.(*GetTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TournamentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.TournamentService",
	HandlerType: (*TournamentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TournamentService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TournamentService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TournamentService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

func init() { proto.RegisterFile("league.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 776 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x55, 0x5e, 0xae, 0xb8, 0x7d, 0xd0, 0x4e, 0x53, 0xe2, 0xba, 0xe9, 0x43, 0x03, 0x94, 0xaa,
	0x12, 0x89, 0x08, 0x0f, 0xa1, 0x22, 0xd8, 0xb4, 0xa8, 0x48, 0x54, 0x2c, 0x4c, 0xc5, 0x86, 0x05,
	0x72, 0x92, 0x69, 0x64, 0xd5, 0xb5, 0x83, 0x3d, 0x09, 0xaa, 0x2a, 0x36, 0xfc, 0x02, 0xdf, 0xc0,
	0xc7, 0x20, 0xb1, 0xe3, 0x17, 0x58, 0xf2, 0x11, 0xcc, 0xcb, 0xf6, 0x24, 0x9e, 0x54, 0x15, 0x9b,
	0xc8, 0xf6, 0xbd, 0xf7, 0x9c, 0x73, 0xcf, 0xdc, 0x3b, 0x0a, 0x2c, 0x04, 0xc4, 0x1b, 0x8c, 0x48,
	0x6b, 0x18, 0x47, 0x34, 0x42, 0xd6, 0xf8, 0x51, 0x97, 0x50, 0xcf, 0x69, 0x0e, 0xa2, 0x68, 0x10,
	0x90, 0xb6, 0x37, 0xf4, 0xdb, 0x5e, 0x18, 0x46, 0xd4, 0xa3, 0x7e, 0x14, 0x26, 0x32, 0x0b, 0x77,
	0x00, 0x8e, 0xfc, 0xa4, 0xe7, 0x0f, 0x03, 0x3f, 0x24, 0x68, 0x09, 0xca, 0x7e, 0xdf, 0x2e, 0xed,
	0x94, 0xf6, 0x6e, 0xb9, 0xec, 0x09, 0xd5, 0xa1, 0x46, 0x7d, 0x1a, 0x10, 0xbb, 0x2c, 0x3e, 0xc9,
	0x17, 0xfc, 0x10, 0x6a, 0x27, 0x64, 0x4c, 0x82, 0x1b, 0xa6, 0xff, 0x2d, 0x81, 0x75, 0x22, 0x94,
	0x21, 0x04, 0xd5, 0xd0, 0xbb, 0x20, 0xaa, 0x44, 0x3c, 0xa3, 0xa7, 0x30, 0xd7, 0x67, 0x3a, 0xfd,
	0x20, 0x61, 0x65, 0x95, 0xbd, 0xf9, 0xce, 0x46, 0x4b, 0x2a, 0x6f, 0xc9, 0xa2, 0xd6, 0x91, 0x8c,
	0xbe, 0x0e, 0x69, 0x7c, 0xe9, 0xa6, 0xb9, 0xe8, 0x3e, 0x58, 0x01, 0x17, 0x91, 0xd8, 0x15, 0x51,
	0xb5, 0x98, 0x57, 0xb1, 0xaf, 0xae, 0x0a, 0xa2, 0x27, 0x30, 0xdf, 0xcf, 0xfa, 0x4b, 0xec, 0xaa,
	0xc8, 0x45, 0x69, 0x6e, 0xde, 0xba, 0xab, 0xa7, 0x39, 0x07, 0xb0, 0xa0, 0xb3, 0xa2, 0x65, 0xa8,
	0x9c, 0x93, 0x4b, 0x25, 0x9b, 0x3f, 0xf2, 0x56, 0xc7, 0x5e, 0x30, 0xca, 0x5a, 0x15, 0x2f, 0x07,
	0xe5, 0xe7, 0x25, 0xfc, 0x00, 0x56, 0x8e, 0x09, 0x95, 0xda, 0x13, 0x97, 0x7c, 0x66, 0xbf, 0xd4,
	0xd4, 0x38, 0x7e, 0x05, 0x48, 0x4f, 0x4c, 0x86, 0xec, 0x54, 0x08, 0xda, 0x83, 0x39, 0x79, 0x8c,
	0x09, 0x4b, 0xe6, 0x62, 0x97, 0x26, 0xed, 0x70, 0xd3, 0x30, 0x76, 0xa1, 0x7e, 0x18, 0x13, 0x8f,
	0x12, 0x15, 0x48, 0x11, 0x18, 0x57, 0x2f, 0xea, 0x4b, 0xae, 0x9a, 0x2b, 0x9e, 0xd1, 0x2e, 0x77,
	0x8b, 0x67, 0x09, 0xbd, 0x45, 0x50, 0x15, 0xc5, 0x87, 0xb0, 0x3a, 0x89, 0x39, 0x53, 0x3e, 0xb2,
	0x61, 0xee, 0x0b, 0xe9, 0x26, 0x3e, 0x4d, 0x3d, 0x48, 0x5f, 0xf1, 0x2e, 0x2c, 0x67, 0x8d, 0x5d,
	0x67, 0xc0, 0x0b, 0xcd, 0xa9, 0x4c, 0x7d, 0xae, 0xb4, 0x74, 0xad, 0x52, 0x07, 0xaa, 0xa7, 0xc4,
	0xbb, 0x30, 0x02, 0xbf, 0x84, 0xda, 0x71, 0x1c, 0x8d, 0x86, 0x46, 0xdd, 0x3b, 0x50, 0xa5, 0xac,
	0x50, 0x8d, 0xcd, 0x42, 0x0a, 0xcf, 0xc1, 0x5c, 0x11, 0xc1, 0x57, 0x50, 0x73, 0xa3, 0x51, 0xd8,
	0x37, 0x96, 0x63, 0xa8, 0x9d, 0xf9, 0x71, 0x42, 0x95, 0x91, 0x93, 0xf5, 0x32, 0x84, 0xee, 0x81,
	0x95, 0x90, 0x5e, 0x14, 0xf6, 0x19, 0x49, 0x31, 0x49, 0xc5, 0xf8, 0x08, 0x25, 0xbd, 0x28, 0x26,
	0x6c, 0x28, 0xc5, 0x08, 0x89, 0x17, 0xfc, 0xb3, 0x04, 0x70, 0x1a, 0x8d, 0x62, 0x4e, 0x16, 0x9a,
	0x9d, 0x7f, 0x06, 0xd6, 0x80, 0xb7, 0x97, 0x2e, 0xcc, 0x56, 0x06, 0x9f, 0xd5, 0xb5, 0x44, 0xff,
	0x6a, 0x67, 0x54, 0x36, 0x5f, 0x99, 0x98, 0xf7, 0x55, 0x58, 0x19, 0xd1, 0xad, 0xab, 0x82, 0xce,
	0x1b, 0x98, 0xd7, 0xaa, 0x0d, 0xb3, 0x7f, 0x57, 0x9f, 0x7d, 0x0d, 0x46, 0x54, 0xe9, 0xab, 0xd0,
	0x80, 0x35, 0x76, 0xc0, 0xb9, 0xaa, 0x74, 0x1d, 0xf0, 0x3b, 0xb8, 0x33, 0x1d, 0x50, 0xc7, 0xcf,
	0xf6, 0x95, 0xe6, 0x9f, 0xd5, 0x0a, 0xa0, 0x62, 0x83, 0xae, 0x9e, 0x86, 0xf7, 0xa1, 0x3e, 0x81,
	0x77, 0xdd, 0xd4, 0xbd, 0x9d, 0x12, 0x95, 0x51, 0xb3, 0xab, 0x30, 0xc7, 0x54, 0xd3, 0x67, 0x62,
	0xd6, 0xb2, 0xf0, 0x29, 0x34, 0xe4, 0xbe, 0xdc, 0x88, 0x9b, 0x9f, 0xc0, 0xc4, 0xc9, 0x4d, 0x59,
	0xa7, 0x82, 0xcc, 0x1e, 0xbb, 0x88, 0xfa, 0xff, 0x2a, 0x3b, 0x3f, 0xca, 0xb0, 0x28, 0xd7, 0xe7,
	0x3d, 0x89, 0xc7, 0x7e, 0x8f, 0xa0, 0x0f, 0x50, 0x3d, 0xf1, 0x99, 0xc8, 0xf5, 0x4c, 0xc0, 0xf4,
	0x95, 0xe5, 0x38, 0xa6, 0x90, 0x14, 0x81, 0x1b, 0xdf, 0x7e, 0xff, 0xf9, 0x5e, 0x5e, 0x41, 0xb7,
	0xdb, 0x32, 0xa7, 0xad, 0xee, 0x24, 0xf4, 0x09, 0x2c, 0xa9, 0x1c, 0x65, 0xb7, 0xb8, 0xe1, 0x3e,
	0x71, 0x9a, 0xe6, 0xa0, 0x42, 0x77, 0x04, 0x7a, 0x1d, 0x4f, 0xa3, 0x1f, 0x94, 0xf6, 0xd1, 0x47,
	0xa8, 0x30, 0x3d, 0xc8, 0x2e, 0x88, 0x4b, 0xa1, 0xd7, 0x0d, 0x11, 0x85, 0xbb, 0x2d, 0x70, 0xd7,
	0x51, 0x83, 0xe1, 0xfa, 0x3a, 0x70, 0xfb, 0x8a, 0x1b, 0xf5, 0xb5, 0xf3, 0xab, 0x0c, 0x2b, 0xb9,
	0x85, 0xa9, 0x57, 0x5d, 0xe5, 0xd5, 0xa6, 0x86, 0x5c, 0x9c, 0x69, 0x67, 0x6b, 0x56, 0x58, 0xb1,
	0x6f, 0x08, 0xf6, 0x35, 0xb4, 0x9a, 0x76, 0xa5, 0x0d, 0x30, 0x3a, 0xcf, 0x7c, 0xdb, 0x9e, 0xb4,
	0xa6, 0x30, 0x57, 0xce, 0xce, 0xec, 0x04, 0xc5, 0xb4, 0x25, 0x98, 0x6c, 0x6c, 0x62, 0xe2, 0x1e,
	0x9e, 0x49, 0x0f, 0x9b, 0x46, 0xc1, 0x29, 0xcd, 0xe6, 0x8c, 0xa8, 0xe2, 0xc0, 0x82, 0xa3, 0x89,
	0x1c, 0x03, 0x87, 0xb2, 0xb3, 0x6b, 0x89, 0xbf, 0x18, 0x8f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x22, 0x1c, 0x1c, 0x77, 0x98, 0x08, 0x00, 0x00,
}
