// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pilotari.proto

package v1beta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pilotari struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pilotari) Reset()         { *m = Pilotari{} }
func (m *Pilotari) String() string { return proto.CompactTextString(m) }
func (*Pilotari) ProtoMessage()    {}
func (*Pilotari) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{0}
}
func (m *Pilotari) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pilotari.Unmarshal(m, b)
}
func (m *Pilotari) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pilotari.Marshal(b, m, deterministic)
}
func (dst *Pilotari) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pilotari.Merge(dst, src)
}
func (m *Pilotari) XXX_Size() int {
	return xxx_messageInfo_Pilotari.Size(m)
}
func (m *Pilotari) XXX_DiscardUnknown() {
	xxx_messageInfo_Pilotari.DiscardUnknown(m)
}

var xxx_messageInfo_Pilotari proto.InternalMessageInfo

func (m *Pilotari) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Pilotari) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Pilotari) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Pilotari) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type GetPilotarisRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPilotarisRequest) Reset()         { *m = GetPilotarisRequest{} }
func (m *GetPilotarisRequest) String() string { return proto.CompactTextString(m) }
func (*GetPilotarisRequest) ProtoMessage()    {}
func (*GetPilotarisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{1}
}
func (m *GetPilotarisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPilotarisRequest.Unmarshal(m, b)
}
func (m *GetPilotarisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPilotarisRequest.Marshal(b, m, deterministic)
}
func (dst *GetPilotarisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPilotarisRequest.Merge(dst, src)
}
func (m *GetPilotarisRequest) XXX_Size() int {
	return xxx_messageInfo_GetPilotarisRequest.Size(m)
}
func (m *GetPilotarisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPilotarisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPilotarisRequest proto.InternalMessageInfo

type GetPilotarisResponse struct {
	Pilotaris            []*Pilotari `protobuf:"bytes,1,rep,name=pilotaris,proto3" json:"pilotaris,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPilotarisResponse) Reset()         { *m = GetPilotarisResponse{} }
func (m *GetPilotarisResponse) String() string { return proto.CompactTextString(m) }
func (*GetPilotarisResponse) ProtoMessage()    {}
func (*GetPilotarisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{2}
}
func (m *GetPilotarisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPilotarisResponse.Unmarshal(m, b)
}
func (m *GetPilotarisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPilotarisResponse.Marshal(b, m, deterministic)
}
func (dst *GetPilotarisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPilotarisResponse.Merge(dst, src)
}
func (m *GetPilotarisResponse) XXX_Size() int {
	return xxx_messageInfo_GetPilotarisResponse.Size(m)
}
func (m *GetPilotarisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPilotarisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPilotarisResponse proto.InternalMessageInfo

func (m *GetPilotarisResponse) GetPilotaris() []*Pilotari {
	if m != nil {
		return m.Pilotaris
	}
	return nil
}

type CreatePilotariRequest struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePilotariRequest) Reset()         { *m = CreatePilotariRequest{} }
func (m *CreatePilotariRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePilotariRequest) ProtoMessage()    {}
func (*CreatePilotariRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{3}
}
func (m *CreatePilotariRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePilotariRequest.Unmarshal(m, b)
}
func (m *CreatePilotariRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePilotariRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePilotariRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePilotariRequest.Merge(dst, src)
}
func (m *CreatePilotariRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePilotariRequest.Size(m)
}
func (m *CreatePilotariRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePilotariRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePilotariRequest proto.InternalMessageInfo

func (m *CreatePilotariRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreatePilotariRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreatePilotariRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreatePilotariRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreatePilotariResponse struct {
	Pilotari             *Pilotari `protobuf:"bytes,1,opt,name=Pilotari,proto3" json:"Pilotari,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePilotariResponse) Reset()         { *m = CreatePilotariResponse{} }
func (m *CreatePilotariResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePilotariResponse) ProtoMessage()    {}
func (*CreatePilotariResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{4}
}
func (m *CreatePilotariResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePilotariResponse.Unmarshal(m, b)
}
func (m *CreatePilotariResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePilotariResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePilotariResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePilotariResponse.Merge(dst, src)
}
func (m *CreatePilotariResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePilotariResponse.Size(m)
}
func (m *CreatePilotariResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePilotariResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePilotariResponse proto.InternalMessageInfo

func (m *CreatePilotariResponse) GetPilotari() *Pilotari {
	if m != nil {
		return m.Pilotari
	}
	return nil
}

type GetPilotariRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPilotariRequest) Reset()         { *m = GetPilotariRequest{} }
func (m *GetPilotariRequest) String() string { return proto.CompactTextString(m) }
func (*GetPilotariRequest) ProtoMessage()    {}
func (*GetPilotariRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{5}
}
func (m *GetPilotariRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPilotariRequest.Unmarshal(m, b)
}
func (m *GetPilotariRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPilotariRequest.Marshal(b, m, deterministic)
}
func (dst *GetPilotariRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPilotariRequest.Merge(dst, src)
}
func (m *GetPilotariRequest) XXX_Size() int {
	return xxx_messageInfo_GetPilotariRequest.Size(m)
}
func (m *GetPilotariRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPilotariRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPilotariRequest proto.InternalMessageInfo

func (m *GetPilotariRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetPilotariResponse struct {
	Pilotari             *Pilotari `protobuf:"bytes,1,opt,name=Pilotari,proto3" json:"Pilotari,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPilotariResponse) Reset()         { *m = GetPilotariResponse{} }
func (m *GetPilotariResponse) String() string { return proto.CompactTextString(m) }
func (*GetPilotariResponse) ProtoMessage()    {}
func (*GetPilotariResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilotari_183d7a58d538d357, []int{6}
}
func (m *GetPilotariResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPilotariResponse.Unmarshal(m, b)
}
func (m *GetPilotariResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPilotariResponse.Marshal(b, m, deterministic)
}
func (dst *GetPilotariResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPilotariResponse.Merge(dst, src)
}
func (m *GetPilotariResponse) XXX_Size() int {
	return xxx_messageInfo_GetPilotariResponse.Size(m)
}
func (m *GetPilotariResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPilotariResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPilotariResponse proto.InternalMessageInfo

func (m *GetPilotariResponse) GetPilotari() *Pilotari {
	if m != nil {
		return m.Pilotari
	}
	return nil
}

func init() {
	proto.RegisterType((*Pilotari)(nil), "v1beta.Pilotari")
	proto.RegisterType((*GetPilotarisRequest)(nil), "v1beta.GetPilotarisRequest")
	proto.RegisterType((*GetPilotarisResponse)(nil), "v1beta.GetPilotarisResponse")
	proto.RegisterType((*CreatePilotariRequest)(nil), "v1beta.CreatePilotariRequest")
	proto.RegisterType((*CreatePilotariResponse)(nil), "v1beta.CreatePilotariResponse")
	proto.RegisterType((*GetPilotariRequest)(nil), "v1beta.GetPilotariRequest")
	proto.RegisterType((*GetPilotariResponse)(nil), "v1beta.GetPilotariResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PilotariServiceClient is the client API for PilotariService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PilotariServiceClient interface {
	// List returns all available Pilotaris
	List(ctx context.Context, in *GetPilotarisRequest, opts ...grpc.CallOption) (*GetPilotarisResponse, error)
	// Create creates a new Pilotari
	Create(ctx context.Context, in *CreatePilotariRequest, opts ...grpc.CallOption) (*CreatePilotariResponse, error)
	// Get return a Pilotari
	Get(ctx context.Context, in *GetPilotariRequest, opts ...grpc.CallOption) (*GetPilotariResponse, error)
}

type pilotariServiceClient struct {
	cc *grpc.ClientConn
}

func NewPilotariServiceClient(cc *grpc.ClientConn) PilotariServiceClient {
	return &pilotariServiceClient{cc}
}

func (c *pilotariServiceClient) List(ctx context.Context, in *GetPilotarisRequest, opts ...grpc.CallOption) (*GetPilotarisResponse, error) {
	out := new(GetPilotarisResponse)
	err := c.cc.Invoke(ctx, "/v1beta.PilotariService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotariServiceClient) Create(ctx context.Context, in *CreatePilotariRequest, opts ...grpc.CallOption) (*CreatePilotariResponse, error) {
	out := new(CreatePilotariResponse)
	err := c.cc.Invoke(ctx, "/v1beta.PilotariService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotariServiceClient) Get(ctx context.Context, in *GetPilotariRequest, opts ...grpc.CallOption) (*GetPilotariResponse, error) {
	out := new(GetPilotariResponse)
	err := c.cc.Invoke(ctx, "/v1beta.PilotariService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PilotariServiceServer is the server API for PilotariService service.
type PilotariServiceServer interface {
	// List returns all available Pilotaris
	List(context.Context, *GetPilotarisRequest) (*GetPilotarisResponse, error)
	// Create creates a new Pilotari
	Create(context.Context, *CreatePilotariRequest) (*CreatePilotariResponse, error)
	// Get return a Pilotari
	Get(context.Context, *GetPilotariRequest) (*GetPilotariResponse, error)
}

func RegisterPilotariServiceServer(s *grpc.Server, srv PilotariServiceServer) {
	s.RegisterService(&_PilotariService_serviceDesc, srv)
}

func _PilotariService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPilotarisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotariServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.PilotariService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotariServiceServer).List(ctx, req.(*GetPilotarisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotariService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePilotariRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotariServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.PilotariService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotariServiceServer).Create(ctx, req.(*CreatePilotariRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotariService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPilotariRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotariServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1beta.PilotariService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotariServiceServer).Get(ctx, req.(*GetPilotariRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PilotariService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta.PilotariService",
	HandlerType: (*PilotariServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PilotariService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PilotariService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PilotariService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pilotari.proto",
}

func init() { proto.RegisterFile("pilotari.proto", fileDescriptor_pilotari_183d7a58d538d357) }

var fileDescriptor_pilotari_183d7a58d538d357 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x4d, 0x81, 0x47, 0xe0, 0xf2, 0xf2, 0x1e, 0x6f, 0x80, 0x97, 0xbe, 0xd2, 0x67, 0x70, 0x56,
	0x84, 0x98, 0x36, 0xe0, 0xce, 0x2d, 0x09, 0x6c, 0x8c, 0x31, 0xb8, 0x35, 0x31, 0x53, 0xbd, 0xe2,
	0x24, 0xa5, 0x53, 0x3b, 0x03, 0x1b, 0xc3, 0xc6, 0xa5, 0x5b, 0xbf, 0xc6, 0xef, 0xf0, 0x17, 0xfc,
	0x10, 0x93, 0x69, 0xa7, 0x50, 0x53, 0x37, 0x6e, 0x5c, 0xde, 0x7b, 0xce, 0xdc, 0x73, 0xce, 0xbd,
	0x19, 0xf8, 0x15, 0xf3, 0x50, 0x28, 0x96, 0x70, 0x2f, 0x4e, 0x84, 0x12, 0xa4, 0xbe, 0x19, 0x07,
	0xa8, 0x98, 0xe3, 0x2e, 0x85, 0x58, 0x86, 0xe8, 0xb3, 0x98, 0xfb, 0x2c, 0x8a, 0x84, 0x62, 0x8a,
	0x8b, 0x48, 0xa6, 0x2c, 0xba, 0x85, 0xc6, 0x79, 0xf6, 0x8e, 0xb8, 0xd0, 0xbc, 0xe5, 0x89, 0x54,
	0x11, 0x5b, 0xa1, 0x6d, 0x0d, 0xac, 0x61, 0x73, 0xb1, 0x6b, 0x10, 0x07, 0x1a, 0x21, 0xcb, 0xc0,
	0x8a, 0x06, 0xf3, 0x9a, 0x74, 0xe1, 0x07, 0xae, 0x18, 0x0f, 0xed, 0xaa, 0x06, 0xd2, 0x82, 0x1c,
	0xc2, 0xcf, 0xf8, 0x4e, 0x44, 0x78, 0x15, 0xad, 0x57, 0x01, 0x26, 0x76, 0x4d, 0x83, 0x2d, 0xdd,
	0x3b, 0xd3, 0x2d, 0xda, 0x83, 0xce, 0x1c, 0x95, 0x71, 0x20, 0x17, 0x78, 0xbf, 0x46, 0xa9, 0xe8,
	0x0c, 0xba, 0xc5, 0xb6, 0x8c, 0x45, 0x24, 0x91, 0x78, 0xd0, 0x34, 0x29, 0xa5, 0x6d, 0x0d, 0xaa,
	0xc3, 0xd6, 0xa4, 0xed, 0xa5, 0x39, 0x3d, 0xc3, 0x5e, 0xec, 0x28, 0xf4, 0xc9, 0x82, 0xde, 0x34,
	0x41, 0xa6, 0x30, 0x47, 0x53, 0x85, 0xef, 0xc8, 0x3a, 0x83, 0xbf, 0x1f, 0xbd, 0x64, 0xb1, 0x8e,
	0x76, 0x47, 0xd0, 0x5e, 0xca, 0x52, 0xe5, 0x0c, 0x3a, 0x02, 0xb2, 0xb7, 0x1c, 0x13, 0x28, 0xb7,
	0x65, 0xed, 0xd9, 0xa2, 0xd3, 0xc2, 0x7e, 0xbf, 0x26, 0x38, 0x79, 0xa9, 0xc0, 0x6f, 0x53, 0x5c,
	0x60, 0xb2, 0xe1, 0xd7, 0x48, 0x2e, 0xa1, 0x76, 0xca, 0xa5, 0x22, 0x7d, 0xf3, 0xae, 0xe4, 0x8c,
	0x8e, 0x5b, 0x0e, 0xa6, 0x26, 0xe8, 0xbf, 0xc7, 0xd7, 0xb7, 0xe7, 0x4a, 0x87, 0xfc, 0xf1, 0x53,
	0x96, 0x9f, 0xdf, 0x8d, 0xdc, 0x40, 0x3d, 0x5d, 0x15, 0xf9, 0x6f, 0x46, 0x94, 0x9e, 0xd1, 0x39,
	0xf8, 0x0c, 0xce, 0x34, 0xfa, 0x5a, 0xa3, 0x47, 0xdb, 0x05, 0x8d, 0x84, 0xcb, 0x13, 0x6b, 0x44,
	0x02, 0xa8, 0xce, 0x51, 0x11, 0xa7, 0xc4, 0xa5, 0x99, 0xdf, 0x2f, 0xc5, 0xb2, 0xe1, 0x54, 0x0f,
	0x77, 0x89, 0xe3, 0x6f, 0xc6, 0xbc, 0x98, 0xc0, 0x7f, 0xd0, 0xfb, 0xdf, 0x06, 0x75, 0xfd, 0xcd,
	0x8e, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x7c, 0x7c, 0xfa, 0x9e, 0x03, 0x00, 0x00,
}
