// Code generated by protoc-gen-go.
// source: league.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	league.proto

It has these top-level messages:
	League
	GetLeaguesRequest
	GetLeaguesResponse
	CreateLeagueResponse
	CreateLeagueRequest
	GetLeagueRequest
	GetLeagueResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// League define a pelota league
type League struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Website string `protobuf:"bytes,2,opt,name=website" json:"website,omitempty"`
}

func (m *League) Reset()                    { *m = League{} }
func (m *League) String() string            { return proto.CompactTextString(m) }
func (*League) ProtoMessage()               {}
func (*League) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeaguesRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeaguesRequest) Reset()                    { *m = GetLeaguesRequest{} }
func (m *GetLeaguesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesRequest) ProtoMessage()               {}
func (*GetLeaguesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetLeaguesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeaguesResponse struct {
	Leagues []*League `protobuf:"bytes,1,rep,name=leagues" json:"leagues,omitempty"`
}

func (m *GetLeaguesResponse) Reset()                    { *m = GetLeaguesResponse{} }
func (m *GetLeaguesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesResponse) ProtoMessage()               {}
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetLeaguesResponse) GetLeagues() []*League {
	if m != nil {
		return m.Leagues
	}
	return nil
}

type CreateLeagueResponse struct {
	Code   int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	League *League `protobuf:"bytes,2,opt,name=league" json:"league,omitempty"`
}

func (m *CreateLeagueResponse) Reset()                    { *m = CreateLeagueResponse{} }
func (m *CreateLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueResponse) ProtoMessage()               {}
func (*CreateLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateLeagueResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type CreateLeagueRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Website string `protobuf:"bytes,2,opt,name=website" json:"website,omitempty"`
}

func (m *CreateLeagueRequest) Reset()                    { *m = CreateLeagueRequest{} }
func (m *CreateLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueRequest) ProtoMessage()               {}
func (*CreateLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLeagueRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeagueRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeagueRequest) Reset()                    { *m = GetLeagueRequest{} }
func (m *GetLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueRequest) ProtoMessage()               {}
func (*GetLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeagueResponse struct {
	League *League `protobuf:"bytes,1,opt,name=league" json:"league,omitempty"`
}

func (m *GetLeagueResponse) Reset()                    { *m = GetLeagueResponse{} }
func (m *GetLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueResponse) ProtoMessage()               {}
func (*GetLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

func init() {
	proto.RegisterType((*League)(nil), "pb.League")
	proto.RegisterType((*GetLeaguesRequest)(nil), "pb.GetLeaguesRequest")
	proto.RegisterType((*GetLeaguesResponse)(nil), "pb.GetLeaguesResponse")
	proto.RegisterType((*CreateLeagueResponse)(nil), "pb.CreateLeagueResponse")
	proto.RegisterType((*CreateLeagueRequest)(nil), "pb.CreateLeagueRequest")
	proto.RegisterType((*GetLeagueRequest)(nil), "pb.GetLeagueRequest")
	proto.RegisterType((*GetLeagueResponse)(nil), "pb.GetLeagueResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LeagueService service

type LeagueServiceClient interface {
	// GetLeagues returns all available League
	GetLeagues(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error)
	// CreateLeague creates a new league
	CreateLeague(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error)
	// GetLeague return a league
	GetLeague(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error)
}

type leagueServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeagueServiceClient(cc *grpc.ClientConn) LeagueServiceClient {
	return &leagueServiceClient{cc}
}

func (c *leagueServiceClient) GetLeagues(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error) {
	out := new(GetLeaguesResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/GetLeagues", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) CreateLeague(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error) {
	out := new(CreateLeagueResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/CreateLeague", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) GetLeague(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error) {
	out := new(GetLeagueResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/GetLeague", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LeagueService service

type LeagueServiceServer interface {
	// GetLeagues returns all available League
	GetLeagues(context.Context, *GetLeaguesRequest) (*GetLeaguesResponse, error)
	// CreateLeague creates a new league
	CreateLeague(context.Context, *CreateLeagueRequest) (*CreateLeagueResponse, error)
	// GetLeague return a league
	GetLeague(context.Context, *GetLeagueRequest) (*GetLeagueResponse, error)
}

func RegisterLeagueServiceServer(s *grpc.Server, srv LeagueServiceServer) {
	s.RegisterService(&_LeagueService_serviceDesc, srv)
}

func _LeagueService_GetLeagues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).GetLeagues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/GetLeagues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).GetLeagues(ctx, req.(*GetLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_CreateLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).CreateLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/CreateLeague",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).CreateLeague(ctx, req.(*CreateLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_GetLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).GetLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/GetLeague",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).GetLeague(ctx, req.(*GetLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeagueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LeagueService",
	HandlerType: (*LeagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeagues",
			Handler:    _LeagueService_GetLeagues_Handler,
		},
		{
			MethodName: "CreateLeague",
			Handler:    _LeagueService_CreateLeague_Handler,
		},
		{
			MethodName: "GetLeague",
			Handler:    _LeagueService_GetLeague_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "league.proto",
}

func init() { proto.RegisterFile("league.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x49, 0x4d, 0x4c,
	0x2f, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe3, 0x62,
	0xf3, 0x01, 0x8b, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0xe5, 0xa9, 0x49, 0xc5, 0x99, 0x25, 0xa9, 0x12,
	0x4c, 0x60, 0x61, 0x18, 0x57, 0x49, 0x9d, 0x4b, 0xd0, 0x3d, 0xb5, 0x04, 0xa2, 0xb5, 0x38, 0x28,
	0xb5, 0x10, 0x48, 0x96, 0x60, 0x33, 0x42, 0xc9, 0x8a, 0x4b, 0x08, 0x59, 0x61, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x0a, 0x17, 0x3b, 0xc4, 0x29, 0xc5, 0x40, 0xc5, 0xcc, 0x1a, 0xdc, 0x46,
	0x5c, 0x7a, 0x05, 0x49, 0x7a, 0x10, 0x55, 0x41, 0x30, 0x29, 0x25, 0x3f, 0x2e, 0x11, 0xe7, 0xa2,
	0xd4, 0xc4, 0x92, 0x54, 0xa8, 0x04, 0x4c, 0x37, 0xd0, 0x9e, 0xe4, 0xfc, 0x14, 0x88, 0x3d, 0xac,
	0x41, 0x60, 0xb6, 0x90, 0x12, 0x17, 0x1b, 0x44, 0x1b, 0xd8, 0xa5, 0xa8, 0x06, 0x42, 0x65, 0x94,
	0x9c, 0xb9, 0x84, 0x51, 0xcd, 0xc3, 0xe9, 0x6c, 0x3c, 0x3e, 0x57, 0xe3, 0x12, 0x80, 0x7b, 0x08,
	0x9f, 0xc7, 0xcd, 0x91, 0x42, 0x08, 0xee, 0x72, 0x84, 0x2b, 0x19, 0x71, 0xb9, 0xd2, 0xe8, 0x24,
	0x23, 0x17, 0x2f, 0x44, 0x28, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x9a, 0x8b, 0x0b,
	0x11, 0x86, 0x42, 0xa2, 0x20, 0x3d, 0x18, 0x81, 0x2f, 0x25, 0x86, 0x2e, 0x0c, 0xb5, 0xd2, 0x91,
	0x8b, 0x07, 0xd9, 0xd3, 0x42, 0xe2, 0x20, 0x75, 0x58, 0x82, 0x41, 0x4a, 0x02, 0x53, 0x02, 0x6a,
	0x84, 0x05, 0x17, 0x27, 0xdc, 0x60, 0x21, 0x11, 0x14, 0x7b, 0x60, 0x9a, 0x45, 0xd1, 0x44, 0x21,
	0x3a, 0x93, 0xd8, 0xc0, 0x29, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x7f, 0x80, 0xa0,
	0x79, 0x02, 0x00, 0x00,
}
