// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Details
	Discipline
	Level
	League
	GetLeaguesRequest
	GetLeaguesResponse
	CreateLeagueResponse
	CreateLeagueRequest
	GetLeagueRequest
	GetLeagueResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Details struct {
	Website     string `protobuf:"bytes,1,opt,name=website" json:"website,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phonenumber string `protobuf:"bytes,4,opt,name=phonenumber" json:"phonenumber,omitempty"`
	Fax         string `protobuf:"bytes,5,opt,name=fax" json:"fax,omitempty"`
}

func (m *Details) Reset()                    { *m = Details{} }
func (m *Details) String() string            { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()               {}
func (*Details) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Details) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Details) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Details) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Details) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Details) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

type Discipline struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Discipline) Reset()                    { *m = Discipline{} }
func (m *Discipline) String() string            { return proto.CompactTextString(m) }
func (*Discipline) ProtoMessage()               {}
func (*Discipline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Discipline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Discipline) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Level struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Level) Reset()                    { *m = Level{} }
func (m *Level) String() string            { return proto.CompactTextString(m) }
func (*Level) ProtoMessage()               {}
func (*Level) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Level) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Level) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// League define a pelota league
type League struct {
	Name        string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Details     *Details      `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	Levels      []*Level      `protobuf:"bytes,3,rep,name=levels" json:"levels,omitempty"`
	Disciplines []*Discipline `protobuf:"bytes,4,rep,name=disciplines" json:"disciplines,omitempty"`
}

func (m *League) Reset()                    { *m = League{} }
func (m *League) String() string            { return proto.CompactTextString(m) }
func (*League) ProtoMessage()               {}
func (*League) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetDetails() *Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *League) GetLevels() []*Level {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *League) GetDisciplines() []*Discipline {
	if m != nil {
		return m.Disciplines
	}
	return nil
}

type GetLeaguesRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeaguesRequest) Reset()                    { *m = GetLeaguesRequest{} }
func (m *GetLeaguesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesRequest) ProtoMessage()               {}
func (*GetLeaguesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetLeaguesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeaguesResponse struct {
	Leagues []*League `protobuf:"bytes,1,rep,name=leagues" json:"leagues,omitempty"`
}

func (m *GetLeaguesResponse) Reset()                    { *m = GetLeaguesResponse{} }
func (m *GetLeaguesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeaguesResponse) ProtoMessage()               {}
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLeaguesResponse) GetLeagues() []*League {
	if m != nil {
		return m.Leagues
	}
	return nil
}

type CreateLeagueResponse struct {
	Code   int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	League *League `protobuf:"bytes,2,opt,name=league" json:"league,omitempty"`
}

func (m *CreateLeagueResponse) Reset()                    { *m = CreateLeagueResponse{} }
func (m *CreateLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueResponse) ProtoMessage()               {}
func (*CreateLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateLeagueResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

type CreateLeagueRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Website string `protobuf:"bytes,2,opt,name=website" json:"website,omitempty"`
}

func (m *CreateLeagueRequest) Reset()                    { *m = CreateLeagueRequest{} }
func (m *CreateLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLeagueRequest) ProtoMessage()               {}
func (*CreateLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLeagueRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type GetLeagueRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetLeagueRequest) Reset()                    { *m = GetLeagueRequest{} }
func (m *GetLeagueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueRequest) ProtoMessage()               {}
func (*GetLeagueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetLeagueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLeagueResponse struct {
	League *League `protobuf:"bytes,1,opt,name=league" json:"league,omitempty"`
}

func (m *GetLeagueResponse) Reset()                    { *m = GetLeagueResponse{} }
func (m *GetLeagueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeagueResponse) ProtoMessage()               {}
func (*GetLeagueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetLeagueResponse) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

func init() {
	proto.RegisterType((*Details)(nil), "pb.Details")
	proto.RegisterType((*Discipline)(nil), "pb.Discipline")
	proto.RegisterType((*Level)(nil), "pb.Level")
	proto.RegisterType((*League)(nil), "pb.League")
	proto.RegisterType((*GetLeaguesRequest)(nil), "pb.GetLeaguesRequest")
	proto.RegisterType((*GetLeaguesResponse)(nil), "pb.GetLeaguesResponse")
	proto.RegisterType((*CreateLeagueResponse)(nil), "pb.CreateLeagueResponse")
	proto.RegisterType((*CreateLeagueRequest)(nil), "pb.CreateLeagueRequest")
	proto.RegisterType((*GetLeagueRequest)(nil), "pb.GetLeagueRequest")
	proto.RegisterType((*GetLeagueResponse)(nil), "pb.GetLeagueResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LeagueService service

type LeagueServiceClient interface {
	// List returns all available League
	List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error)
	// Get return a league
	Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error)
}

type leagueServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeagueServiceClient(cc *grpc.ClientConn) LeagueServiceClient {
	return &leagueServiceClient{cc}
}

func (c *leagueServiceClient) List(ctx context.Context, in *GetLeaguesRequest, opts ...grpc.CallOption) (*GetLeaguesResponse, error) {
	out := new(GetLeaguesResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Create(ctx context.Context, in *CreateLeagueRequest, opts ...grpc.CallOption) (*CreateLeagueResponse, error) {
	out := new(CreateLeagueResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueServiceClient) Get(ctx context.Context, in *GetLeagueRequest, opts ...grpc.CallOption) (*GetLeagueResponse, error) {
	out := new(GetLeagueResponse)
	err := grpc.Invoke(ctx, "/pb.LeagueService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LeagueService service

type LeagueServiceServer interface {
	// List returns all available League
	List(context.Context, *GetLeaguesRequest) (*GetLeaguesResponse, error)
	// Create creates a new league
	Create(context.Context, *CreateLeagueRequest) (*CreateLeagueResponse, error)
	// Get return a league
	Get(context.Context, *GetLeagueRequest) (*GetLeagueResponse, error)
}

func RegisterLeagueServiceServer(s *grpc.Server, srv LeagueServiceServer) {
	s.RegisterService(&_LeagueService_serviceDesc, srv)
}

func _LeagueService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).List(ctx, req.(*GetLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Create(ctx, req.(*CreateLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LeagueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueServiceServer).Get(ctx, req.(*GetLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeagueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LeagueService",
	HandlerType: (*LeagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LeagueService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LeagueService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LeagueService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x9d, 0x97, 0x7a, 0xa3, 0x54, 0xe1, 0x36, 0x2d, 0x56, 0xc4, 0xa2, 0x8c, 0x78, 0x09,
	0x89, 0x18, 0xc2, 0x02, 0xa9, 0xdb, 0x56, 0x42, 0x42, 0x51, 0x17, 0xee, 0x17, 0x8c, 0xe3, 0x4b,
	0x18, 0xc9, 0xb1, 0x8d, 0x67, 0x1a, 0x90, 0x10, 0x12, 0x62, 0xc3, 0x07, 0xb0, 0xe1, 0xbf, 0xf8,
	0x05, 0x3e, 0x84, 0x79, 0x39, 0x38, 0x7d, 0xa0, 0x6e, 0xa2, 0x99, 0x7b, 0xce, 0x3d, 0xf7, 0xdc,
	0x13, 0x0f, 0x8c, 0x24, 0xd5, 0x1b, 0xb1, 0xa4, 0x59, 0x55, 0x97, 0xaa, 0xc4, 0xb0, 0x4a, 0xa7,
	0x0f, 0x56, 0x65, 0xb9, 0xca, 0x29, 0xe6, 0x95, 0x88, 0x79, 0x51, 0x94, 0x8a, 0x2b, 0x51, 0x16,
	0xd2, 0x31, 0xd8, 0x8f, 0x00, 0x06, 0x67, 0xa4, 0xb8, 0xc8, 0x25, 0x46, 0x30, 0xf8, 0x44, 0xa9,
	0x14, 0x8a, 0xa2, 0xe0, 0x38, 0x78, 0xb6, 0x97, 0x34, 0x57, 0x83, 0xf0, 0x2c, 0xab, 0x49, 0xca,
	0x28, 0x74, 0x88, 0xbf, 0xe2, 0x04, 0x7a, 0xb4, 0xd6, 0xdd, 0x51, 0xc7, 0xd6, 0xdd, 0x05, 0x8f,
	0x61, 0x58, 0x7d, 0x28, 0x0b, 0x2a, 0x2e, 0xd7, 0x29, 0xd5, 0x51, 0xd7, 0x62, 0xed, 0x12, 0x8e,
	0xa1, 0xf3, 0x9e, 0x7f, 0x8e, 0x7a, 0x16, 0x31, 0x47, 0x36, 0x07, 0x38, 0x13, 0x72, 0x29, 0xaa,
	0x5c, 0x14, 0x84, 0xfb, 0x10, 0x8a, 0xcc, 0xdb, 0xd0, 0x27, 0x33, 0x47, 0x09, 0x95, 0x93, 0x9f,
	0xef, 0x2e, 0xec, 0x05, 0xf4, 0x16, 0xb4, 0xa1, 0xfc, 0x8e, 0xf4, 0x5f, 0x01, 0xf4, 0x17, 0xc4,
	0x57, 0x97, 0x84, 0x08, 0xdd, 0x82, 0xaf, 0x9b, 0x45, 0xed, 0x19, 0x1f, 0xc3, 0x20, 0x73, 0x51,
	0xd8, 0xb6, 0xe1, 0x7c, 0x38, 0xab, 0xd2, 0x99, 0x4f, 0x27, 0x69, 0x30, 0x7c, 0x08, 0xfd, 0xdc,
	0x0c, 0x95, 0x7a, 0xe7, 0x8e, 0x66, 0xed, 0x19, 0x96, 0xb5, 0x91, 0x78, 0x00, 0x5f, 0xc2, 0x30,
	0xdb, 0xee, 0x22, 0xf5, 0xfe, 0x86, 0xb7, 0x6f, 0xd5, 0xb6, 0xe5, 0xa4, 0x4d, 0x61, 0x4f, 0xe1,
	0xde, 0x5b, 0x52, 0xce, 0x9c, 0x4c, 0xe8, 0xa3, 0xfe, 0x55, 0x37, 0x99, 0x64, 0x27, 0x80, 0x6d,
	0xa2, 0xac, 0xf4, 0x7f, 0x49, 0xf8, 0x08, 0x06, 0xb9, 0x2b, 0x69, 0xb2, 0x19, 0x06, 0xce, 0x94,
	0x29, 0x25, 0x0d, 0xc4, 0xce, 0x61, 0x72, 0x5a, 0x13, 0x57, 0xe4, 0x81, 0xa6, 0x5b, 0xcf, 0x59,
	0x96, 0x99, 0x9b, 0xd3, 0x4b, 0xec, 0x19, 0x99, 0xd9, 0xd2, 0xb0, 0x7c, 0x16, 0x6d, 0x41, 0x8f,
	0xb0, 0x53, 0x38, 0xd8, 0xd5, 0xbb, 0xd5, 0x76, 0xfb, 0xdb, 0x0a, 0x77, 0xbe, 0x2d, 0xf6, 0x04,
	0xc6, 0xdb, 0x85, 0xfe, 0xb7, 0xf8, 0x9b, 0x56, 0x42, 0x5b, 0xe7, 0xff, 0x5c, 0x06, 0xb7, 0xb9,
	0x9c, 0x7f, 0x0b, 0x61, 0xe4, 0x4a, 0x17, 0xee, 0x71, 0xe0, 0x3b, 0xe8, 0x2e, 0x84, 0x1e, 0x73,
	0x68, 0xd8, 0xd7, 0x62, 0x9f, 0x1e, 0x5d, 0x2d, 0xbb, 0x61, 0xec, 0xe0, 0xfb, 0xef, 0x3f, 0x3f,
	0xc3, 0x11, 0x0e, 0xe3, 0xcd, 0xab, 0xd8, 0x67, 0x8a, 0x17, 0xd0, 0x77, 0x19, 0xe0, 0x7d, 0xd3,
	0x76, 0x43, 0x1e, 0xd3, 0xe8, 0x3a, 0xe0, 0x15, 0x8f, 0xac, 0xe2, 0x98, 0xb5, 0x15, 0x4f, 0x82,
	0xe7, 0x78, 0x0e, 0x1d, 0x3d, 0x1f, 0x27, 0x3b, 0x46, 0x1a, 0xb9, 0xc3, 0x2b, 0x55, 0xaf, 0x35,
	0xb5, 0x5a, 0x13, 0xc4, 0x96, 0x56, 0xfc, 0xc5, 0x44, 0xf7, 0x35, 0xed, 0xdb, 0xc7, 0xfe, 0xfa,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x8f, 0x52, 0x05, 0x1f, 0x04, 0x00, 0x00,
}
